# Generated by Django 4.1.2 on 2022-10-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
