# Generated by Django 4.1.2 on 2022-12-22 07:31

from django.db import migrations, models
import utils.files


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=utils.files.SetUploadPath('user/avatars')),
        ),
    ]
